### PR TITLE
44 skos registry per request

### PR DESCRIPTION
**Pull request by koenedaele**
PR for review. Not sure about merging yet.

### CODE REVIEW

**Comment by koenedaele** [comment]
> This `if settings['skosregistry_location'] == 'registry':` would keep the old behaviour of one global registry, right? What would be the use case of this?
> I assume you would have to pass your own factory which will make sure that everything is thread-safe. Or only if the user/project knows that all the providers it uses can be used in parallel?

If you're only using the in-memory providers such as SimpleCsvProvider, DictionaryProvider, RDFProvider, the global registry is fine. 

Currently, this maintains backwards compatibility and it's even the default setting because of backwards compatibility. I am considering deprecating it and issueing a user warning and removing it in version 1.0 or so. What do you think?

**Comment by Wim-De-Clercq** [comment]
> If you're only using the in-memory providers such as SimpleCsvProvider, DictionaryProvider, RDFProvider, the global registry is fine.

Agree, maybe this is also a reason to keep the global registry without deprecating it... if it does no harm then it's probably more performant to just make it once and reuse.

I wonder if it's worth to give the registry a boolean flag `is_global` or something so libraries who add providers to the registry can check on this, and issue warnings/raise early themselves. 

For example, if I were to make a project, and decide to include atramhasis' skos, that would imply I should also use a request registry because they use sqlalchemy providers. I think it'd be nice if in this case atramhasis could warn me or even raise when i did not configure a request-local registry, instead of relying on the developer to know that atramhasis is using non-global-safe providers.


---- 

sidenote, how is the provider registration going to go on request registries. I assume that every request, a new registry is empty without providers? Currently the providers are added at application launch time via `includeme`.

**Comment by koenedaele** [comment]
> sidenote, how is the provider registration going to go on request registries. I assume that every request, a new registry is empty without providers? Currently the providers are added at application launch time via `includeme`.

Yes, I've been thinking about doing things like providers that only get loaded when they're actually accessed as a a way of speeding a few things up, but it seems overkill for what it does. So, not really a priority. A long as a provider doesn't do a lot when it get instantiated, building the registry should be fine. There were a few providers that always did calls on instantiation, but those were rewritten a while back.

The current code that lives in `includeme` would be run by the registry factory function.

**Comment by koenedaele** [comment]
> > If you're only using the in-memory providers such as SimpleCsvProvider, DictionaryProvider, RDFProvider, the global registry is fine.
> 
> Agree, maybe this is also a reason to keep the global registry without deprecating it... if it does no harm then it's probably more performant to just make it once and reuse. And only projects that need it, can use the request registry.
> 
> I wonder if it's worth to give the registry a boolean flag `is_global` or something so libraries who add providers to the registry can check on this, and issue warnings/raise early themselves.
> 
> For example, if I were to make a project, and decide to include atramhasis' skos, that would imply I should also use a request registry because they use sqlalchemy providers. I think it'd be nice if in this case atramhasis could warn me or even raise when i did not configure a request-local registry, instead of relying on the developer to know that atramhasis is using non-global-safe providers.

Good idea. But since a skosprovider_sqlalchemy can work with a global registry outside of a web context (in a cli script), I'd work with warnings that can be ignored if needed.

**Comment by koenedaele** [comment]
@Wim-De-Clercq Can you have a look at koenedaele/skosprovider#63 ? This adds an instance_scope keyword to a registry with three options: _single_ (for scripts or single process web applications), _threaded_global_ (threaded pyramid with a global registry), _threaded_thread_ (threaded pyramid with a regsitry per request). So a SQLAlchemyProvider would be safe with _single_ and _threaded_thread_ registries.

**Comment by Wim-De-Clercq** [comment]
> A long as a provider doesn't do a lot when it get instantiated, building the registry should be fine. There were a few providers that always did calls on instantiation, but those were rewritten a while back.

The `skos_registry` added to the request via `add_request_method` itself is also lazy loaded per request already.
And then still applications could decide to create the dictproviders and others that they know are threadsafe globally outside of `def build_registry` and only register them inside.
So I also think it's probably gonna be fine.

**Pull request merged**
