### PR TITLE
expand and language added

### LINKED ISSUE #10: Allow client to choose language
Springs from OnroerendErfgoed/skosprovider_atramhasis#2.

I think we might need to do 2 things:

 * Make sure that pyramid_skosprovider honors the current request locale, like here in Atramhasis: https://github.com/OnroerendErfgoed/atramhasis/blob/master/atramhasis/views/views.py#L156 Is this something standard to pyramid or is this something we made up for Atramhasis?
 * Make it possible to override the current request locale with a parmeter in the url. eg /conceptschemes/STYLES/c?language=nl-BE.

/cc @BartSaelen

### LINKED ISSUE #11: Expose the expand method
Currently we're not exposing the expand method. Might be helpful to add it as well.

### PR DESCRIPTION
**Pull request by dieuska**
closed #10 and closed #11

### CODE REVIEW

**Comment by koenedaele** [comment]
Currently the tests fail on py3.3 and py 3.4

**Comment by koenedaele** [comment]
Is it possible to add a test that show the difference between the language parameter and the locale name?

Eg. a test where we set up the DummyRequest with locale_name "en", do the request. Then do the same request with parameter language "nl". And then compare both results to assert that they're different?

**Comment by koenedaele** [comment]
Could you also update the service documentation?

**Comment by dieuska** [comment]
allright, problem of 3.3/3.4 was the difference "import fixtures" vs "import .fixtures" and the different testing libs. I ll add the test and service documentation

**Comment by dieuska** [comment]
when writing the tests that you asked, I discovered a dependency to Skosprovider that we also need to adapt to fix the language-ticket:
Skosprovider->registry.py-> find(). This method also need to pass by 'language' because it is used in pyramid_skosprovider. So I first need to make a pull request for that one...

**Comment by koenedaele** [comment]
Yes, that's already registered as koenedaele/skosprovider#10.

**Comment by koenedaele** [comment]
The issue in koenedaele/skosprovider#10 has been solved.

**Pull request merged**
